# Spark metrics → Prometheus servlet (ЛР 4)
# https://spark.apache.org/docs/latest/monitoring.html

*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet

master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
worker.source.jvm.class=org.apache.spark.metrics.source.JvmSource

master.sink.prometheusServlet.path=/metrics/master/prometheus/
worker.sink.prometheusServlet.path=/metrics/prometheus/
